baseURL = "/"
languageCode = "en-us"
title = "AI News Summarizer"
theme = "PaperMod"

[params]
  defaultTheme = "auto"  # Enables light/dark mode toggle
  ShowReadingTime = false
  ShowShareButtons = false
  ShowToc = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowWordCount = false
  disableScrollToTop = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "AI"
    url = "/categories/AI/"
    weight = 1

  [[menu.main]]
    name = "Sport"
    url = "/categories/sport/"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/categories/research/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.renderer]
      unsafe = true
