baseURL = "https://weeklynews.dev/"
languageCode = "en-us"
title = "AI News Summarizer"
theme = "PaperMod"

[services]
  [services.googleAnalytics]
    id = "G-D3JHE8ZJNE"
  [services.disqus]
    shortname = ""

[params]
  defaultTheme = "auto"  # Enables light/dark mode toggle
  ShowReadingTime = false
  ShowShareButtons = false
  ShowToc = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowWordCount = false
  disableScrollToTop = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "AI"
    url = "/categories/AI/"
    weight = 1

  [[menu.main]]
    name = "Tech"
    url = "/categories/tech/"
    weight = 2

  [[menu.main]]
    name = "Science"
    url = "/categories/science/"
    weight = 3
  
  [[menu.main]]
    name = "Health"
    url = "/categories/health/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.renderer]
      unsafe = true


